name: Build Android APK
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.35.1'

      - run: flutter pub get

      # 👇 Patch namespace in build.gradle
      - name: Patch on_audio_query_android namespace
        run: |
          FILE="$HOME/.pub-cache/hosted/pub.dev/on_audio_query_android-1.1.0/android/build.gradle"
          if grep -q "namespace" $FILE; then
            echo "✅ Namespace already exists"
          else
            sed -i '/android {/a \    namespace "com.lucasjosino.on_audio_query_android"' $FILE
            echo "✅ Namespace added to $FILE"
          fi

      # 👇 Remove package attribute from AndroidManifest.xml
      - name: Patch on_audio_query_android manifest
        run: |
          MANIFEST="$HOME/.pub-cache/hosted/pub.dev/on_audio_query_android-1.1.0/android/src/main/AndroidManifest.xml"
          sed -i 's/package="com.lucasjosino.on_audio_query"//g' $MANIFEST
          echo "✅ Removed package attribute from $MANIFEST"

      - name: Build APK
        run: flutter build apk --release

      - uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
